#!/usr/bin/env bash
# ripped off https://github.com/jessarcher/dotfiles/blob/master/install

DOTFILES=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)

rm -rf "$HOME"/.tmux
ln -s "$DOTFILES"/tmux/.tmux "$HOME"/.tmux
ln -sf "$DOTFILES"/tmux/tmux.conf "$HOME"/.tmux.conf

if [ ! -d "$HOME"/.config ]; then
  mkdir "$HOME"/.config
fi
rm -rf "$HOME"/.config/nvim
ln -s "$DOTFILES"/nvim "$HOME"/.config/nvim

# rm -rf "$HOME"/.config/lazygit
# ln -s "$DOTFILES"/lazygit "$HOME"/.config/lazygit
#
# rm -rf "$HOME"/.vale.ini
# ln -s "$DOTFILES"/.vale.ini "$HOME"/.vale.ini

ln -sf "$DOTFILES"/zsh/.zshrc "$HOME"/.zshrc
ln -sf "$DOTFILES"/zsh/.p10k.zsh "$HOME"/.p10k.zsh
rm -rf "$HOME"/.config/zsh
ln -s "$DOTFILES"/zsh "$HOME"/.config/zsh

if [ ! -d "$HOME/.oh-my-zsh" ]; then
	KEEP_ZSHRC=yes sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
fi
sh -c "git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k"

# vale sync
